### ISSUE TITLE
Improve commit messages quality

### ISSUE THREAD

**Issue by EdNgulele** [Azeite/Tierra#1]
Dear @Azeite, I was looking at your project specially your contributions and I noticed that you've been writing commit messages like:

* trying to fix errors
* Attempting to fix https error
* Delete CNAME

It's extremely hard to understand your contribution if you don't explain it properly. Hard for us and for you, because 6months from now you won't remember what you meant by "trying to fix errors".

I recommend you follow this [commit message style guide](https://udacity.github.io/git-styleguide/). This will only make your job easier (and ours) :)

Cheers.

**Comment by Azeite** [comment]
Thank you Eddie
